### ISSUE TITLE
Long contention Warning Android

### ISSUE THREAD

**Issue by HugoGresse** [keenlabs/KeenClient-Java#74] opened 2016-07-04 12:16 UTC
I'm using latest KeenClient in an Android app and the follwoing lgos keep appering : 

```
07-04 08:10:04.925 7491-8567/io.gresse.hugo.anecdote W/art: Long monitor contention event with owner method=java.lang.String io.a.a.b.g.a(io.a.a.b.q, java.net.URL, java.util.Map) from KeenClient.java:1389 waiters=2 for 1.328s
07-04 08:10:05.574 7491-8574/io.gresse.hugo.anecdote W/art: Long monitor contention event with owner method=java.lang.String io.a.a.b.g.a(io.a.a.b.q, java.net.URL, java.util.Map) from KeenClient.java:1389 waiters=1 for 1.192s
07-04 08:10:06.287 7491-7513/io.gresse.hugo.anecdote W/art: Long monitor contention event with owner method=java.lang.String io.a.a.b.g.a(io.a.a.b.q, java.net.URL, java.util.Map) from KeenClient.java:1389 waiters=1 for 1.264s
07-04 08:10:07.002 7491-8509/io.gresse.hugo.anecdote W/art: Long monitor contention event with owner method=java.lang.String io.a.a.b.g.a(io.a.a.b.q, java.net.URL, java.util.Map) from KeenClient.java:1389 waiters=1 for 1.422s
07-04 08:10:09.039 7491-8567/io.gresse.hugo.anecdote W/art: Long monitor contention event with owner method=java.lang.String io.a.a.b.g.a(io.a.a.b.q, java.net.URL, java.util.Map) from KeenClient.java:1389 waiters=1 for 2.508s
07-04 08:10:09.758 7491-8574/io.gresse.hugo.anecdote W/art: Long monitor contention event with owner method=java.lang.String io.a.a.b.g.a(io.a.a.b.q, java.net.URL, java.util.Map) from KeenClient.java:1389 waiters=0 for 641ms
07-04 08:11:26.995 7491-8509/io.gresse.hugo.anecdote W/art: Long monitor contention event with owner method=java.lang.String io.a.a.b.g.a(io.a.a.b.q, java.net.URL, java.util.Map) from KeenClient.java:1389 waiters=0 for 499ms
07-04 08:11:27.650 7491-8567/io.gresse.hugo.anecdote W/art: Long monitor contention event with owner method=java.lang.String io.a.a.b.g.a(io.a.a.b.q, java.net.URL, java.util.Map) from KeenClient.java:1389 waiters=1 for 971ms
07-04 08:11:28.910 7491-8574/io.gresse.hugo.anecdote W/art: Long monitor contention event with owner method=java.lang.String io.a.a.b.g.a(io.a.a.b.q, java.net.URL, java.util.Map) from KeenClient.java:1389 waiters=2 for 2.045s
```

It seems to appear very often...

**Comment by dkador** [comment] 2016-07-05 04:25
Thanks for the report. Is it possible you're adding many events but using `addEvent` instead of `queueEvent`? See https://github.com/keenlabs/KeenClient-Java#single-event-vs-batch for details.

**Comment by HugoGresse** [comment] 2016-07-07 07:26
Well, yes, every event is sended independently but not at the same exact time, like some seconds diff (user action tracking). But I've the feeling that it should be fixed anyway

**Comment by dkador** [comment] 2016-07-07 17:42
The contention is happening because the `addEvent` method you're calling is uploading one event at a time to Keen. We take a lock on each of these requests to make sure we handle a number of error scenarios.

The fix for this is to switch to a model of using `queueEvent` instead of `addEvent` in your code. This will simply queue the event on the local device for later sending to Keen. Then you'll want to call `sendQueuedEvents` or `sendQueuedEventsAsync` to flush whatever's on the device locally.

Alternatively, you can just use `addEventAsync` in place of `addEvent`. This will move uploading events to Keen to a background thread. It won't prevent contention, but it should prevent that contention from impacting your application.

Hope those options make sense. Let me know if not.

**Comment by HugoGresse** [comment] 2016-07-07 17:52
Thanks Daniel for the help. I'm alreayd using addEventAsync. I'll change
the code to use the queue but please fix this issue. You may maybe use some
library like OkHttp to send the event. I know that a library in this case
is a bit overkill and that a library should be lightweight, but It will
work well ( I can guarantee that because I'm using it in the official Teads
SDK for Android to send every tracking event).

Thanks

Le jeu. 7 juil. 2016 à 19:43, Daniel Kador <notifications@github.com> a
écrit :

> The contention is happening because the addEvent method you're calling is
> uploading one event at a time to Keen. We take a lock on each of these
> requests to make sure we handle a number of error scenarios.
>
> The fix for this is to switch to a model of using queueEvent instead of
> addEvent in your code. This will simply queue the event on the local
> device for later sending to Keen. Then you'll want to call
> sendQueuedEvents or sendQueuedEventsAsync to flush whatever's on the
> device locally.
>
> Alternatively, you can just use addEventAsync in place of addEvent. This
> will move uploading events to Keen to a background thread. It won't prevent
> contention, but it should prevent that contention from impacting your
> application.
>
> Hope those options make sense. Let me know if not.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/keenlabs/KeenClient-Java/issues/74#issuecomment-231153373>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAobaTEufjEdzerP0gixTwhSEuPyS9Wfks5qTTqhgaJpZM4JEUZW>
> .
>
-- 
Hugo Gresse
06 09 27 46 20
http://hugo.gresse.io/

**Comment by dkador** [comment] 2016-07-07 17:58
The issue isn't with the actual HTTP call - that part works fine. It's that we take a lock to ensure that we handle multiple error scenarios, the most important of which is making sure we don't send the same locally cached event more than once. From what I can tell, this is working as designed.

That being said, I'm happy to hear suggestions on what should be fixed. And we love to see PRs from our community.

**Comment by dkador** [comment] 2016-08-04 18:54
Closing for now. Please re-open if you'd like to continue the conversation!

**Closed by dkador** 2016-08-04 18:54 UTC
