### ISSUE TITLE
Missing transitive dependencies on Android artifact

### ISSUE THREAD

**Issue by davidschreiber** [keenlabs/KeenClient-Java#81] opened 2016-10-13 14:25 UTC
The artifact `io.keen:keen-client-api-android:5.0.0` hosted on central Maven or JCenter does not bring the transitive dependency to `io.keen:keen-client-java-core:5.0.0` although this library needs to be present as well.

It seems this is a bug with the published artifacts, since the README states that transitive dependencies should be present.

**Comment by Geeber** [comment] 2016-10-17 16:24
Hi David, thanks for reporting this. I can confirm that this was an unintended side-effect of the recent changes we made to how our artifacts are built and packaged. We'll take a look into getting that fixed but it might be a bit since I think we'll have to refactor our build process a bit in order to address it. In the meantime, you should be able to just add `io.keen:keen-client-java-core:5.0.0` to your explicit dependency list in order to get unblocked.

Sorry for the mistake! Feel free to follow this issue for updates on a fix.

**Comment by Geeber** [comment] 2016-10-21 23:25
This should be fixed now; try using version 5.0.1. Let us know if you still have issues. Thanks again for reporting it!

**Closed** 2016-10-21 23:24 UTC
